# Change these first
owner: himalayadevo # Your GitHub organization or username, where this repository lives
repo: medusa_monitoring # The name of this repository

sites:
  - name: Medusadistribution
    url: https://medusadistribution.com/
    baseUrl: /medusa_monitoring
  - name: Frontend
    url: https://beta.medusadistribution.com/
    baseUrl: /medusa_monitoring
  - name: Admin
    url: https://admin.medusadistribution.com/
    baseUrl: /medusa_monitoring
   
  - name: Purchase Order Lines
    url: https://api.tradegecko.com/purchase_order_line_items?limit=250&page=next
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: Stock adjustments API
    url: https://api.tradegecko.com/stock_adjustments/6114387
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: Purchase Orders API
    url: https://api.tradegecko.com/purchase_orders/1711730
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"

  - name: Variants API
    url: https://api.tradegecko.com/variants/70061913
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
      
  - name: TG orders API
    url: https://api.tradegecko.com/orders/91163271
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: Products API
    url: https://api.tradegecko.com/products/39126162
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: Purchase Orders (All Statuses) API
    url: https://api.tradegecko.com/purchase_orders?limit=250&page=next
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: All Variants (archived & active) API
    url: https://api.tradegecko.com/variants?limit=250&status=archived,active
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: All Products (archived & active) API
    url: https://api.tradegecko.com/products?limit=250&status=archived,active
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: Companies API
    url: https://api.tradegecko.com/companies/62791314
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: Sales Orders (All Statuses) API
    url: https://api.tradegecko.com/orders?limit=250&status=archived,active
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: Purchase Order Line Items API
    url: https://api.tradegecko.com/purchase_order_line_items?limit=250&page=next
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: Get Suppliers
    url: https://api.tradegecko.com/companies?company_type=supplier
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
  - name: TAX API
    url: https://api.tradegecko.com/products/35401427
    baseUrl: /medusa_monitoring
    headers:
      - "Authorization: Bearer $SECRET_API"
      - "Content-Type: application/json"
           
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
 
  #cname: demo.upptime.js.org
  baseUrl: /medusa_monitoring
  logoUrl: https://cdn.shopify.com/s/files/1/2221/1809/files/Medusa_Head_32x32.png?v=1510246075
  name: Medusa Monitoring
  theme: dark
  introTitle: ""
  introMessage: Realtime Medusa API Monitoring
  navbar:
    - title: Status
      href: /medusa_monitoring
i18n:
  footer: Medusa Monitoring
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
